apiVersion: container.huisebug.org/v1
kind: RegistryClean
metadata:
  name: registryclean
  namespace: registry-operator-system
spec:
  image: huisebug/dockerregistryclean:latest
  registryurl: registry:5000
  registryauth: d3lmdXNlcjp1anNnWUJGTUtMMTE=
  # pvc: registry-operator-system
  keepimage:
    keepimagenum: 40
    schedule: "0 2 1/1 * *"


