---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-container-huisebug-org-v1-registry
  failurePolicy: Fail
  name: mregistry.kb.io
  rules:
  - apiGroups:
    - container.huisebug.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registries
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-container-huisebug-org-v1-registryclean
  failurePolicy: Fail
  name: mregistryclean.kb.io
  rules:
  - apiGroups:
    - container.huisebug.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registrycleans
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-container-huisebug-org-v1-registry
  failurePolicy: Fail
  name: vregistry.kb.io
  rules:
  - apiGroups:
    - container.huisebug.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registries
  sideEffects: None
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-container-huisebug-org-v1-registryclean
  failurePolicy: Fail
  name: vregistryclean.kb.io
  rules:
  - apiGroups:
    - container.huisebug.org
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - registrycleans
  sideEffects: None
