# permissions for end users to view registrycleans.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: registryclean-viewer-role
rules:
- apiGroups:
  - container.huisebug.org
  resources:
  - registrycleans
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - container.huisebug.org
  resources:
  - registrycleans/status
  verbs:
  - get
